### ISSUE TITLE
`nanotron/the-pile-for-doremi` is empty

### ISSUE THREAD

**Issue by Tonyhao96** [huggingface/nanotron#127]
https://huggingface.co/datasets/nanotron/the-pile-for-doremi/tree/main

I cannot download the dataset, could you please check it?

**Comment by xrsrke** [comment]
@Tonyhao96 Hey. There was a bug in DoReMi's implementation, we have fixed it [[link]](https://github.com/huggingface/nanotron/pull/119) (not merged yet) and rerun the experiment on Fineweb2 (a up comming release dataset)... So the previous experiment results are not legit. Stay tune for the new release

For the new experiment result, check the last images of this tweet: https://twitter.com/xariusrke/status/1774089131351584852
