### ISSUE TITLE
Where is the "nanotron format" defined?

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/nanotron#176]
I see that any(?) hf model can be converted to nanotron format with this [script](https://github.com/huggingface/nanotron/blob/main/examples/llama/convert_hf_to_nanotron.py).

Is there documentation describing this format?

Can any model that may be loaded with AutoModelForCausalLM be converted to nanotron format for training?

**Comment by yardenas** [comment]
@RonanKMcGovern, not really tbh, it's tailored for llama2. We're (@AleHD, @TJ-Solergibert) working on an extension to llama3, but generally speaking it wouldn't work for any hugging face model.

**Comment by RonanKMcGovern** [comment]
Noted, thanks. I guess this is a powerful library to quickly test the performance of different datasets.
