### ISSUE TITLE
Request for detailed FineWeb-ablation-models training strategy & hyperparams

### ISSUE THREAD

**Issue by JefferyChen453** [huggingface/nanotron#201]
I'm trying to re-produce the evaluaions of your FineWeb-ablation-models, but my results are not comparable to yours under the same setting for model. May I ask for the training config file for your [ablation-models](https://huggingface.co/collections/HuggingFaceFW/dataset-comparison-models-662457b0d213e8c14fe47f32#/)?

**Comment by koalazf99** [comment]
Hi~ @JefferyChen453 
I also want to know the training config of the fineweb ablation models
What is your hyper-parameter? May I ask what computing resource you are using currently?

**Comment by guipenedo** [comment]
Hi,
for the evaluations, see the comments here: https://huggingface.co/datasets/HuggingFaceFW/fineweb/blob/main/lighteval_tasks.py
for training: https://huggingface.co/datasets/HuggingFaceFW/fineweb/discussions/39

**Comment by koalazf99** [comment]
Thanks!
