### ISSUE TITLE
Circular import 

### ISSUE THREAD

**Issue by Na00s** [huggingface/nanotron#213]
Hi everyone,

I have the same exact problem as [issue #191](https://github.com/huggingface/nanotron/issues/191) when trying to run the following .sh file:
accelerate launch --num_processes=1 -m
lighteval accelerate
--model_args="pretrained=Na0s/Llama-3.1-8B-Pruned-4-Layers_LoRA-PEFT-3.0"
--tasks "helm|commonsenseqa|0|0,original|mmlu|0|0,leaderboard|arc:challenge|0|0,helm|hellaswag|0|0,helm|piqa|0|0,helm|siqa|0|0,lighteval|triviaqa|0|0,helm|openbookqa|0|0,helm|boolq|0|0,helm|quac|0|0,leaderboard|gsm8k|0|0,"
--output_dir="./evals/"

All my packages are up to date

Fixes that I tried
- Tried to do  pip install -e . again
- Tried to do  pip install nanotron again

The problems unfortunately persists.

Thanks for your help.

**Comment by xrsrke** [comment]
Hi could u install directly from the repo?

**Comment by barney49** [comment]
hello @xrsrke 
Thank you for discussion
I am also facing circular import problem,
I've tried to install it from the repo, but getting same error
![image](https://github.com/user-attachments/assets/7d5b254d-0f24-446e-894a-6a283849652a)

**Comment by barney49** [comment]
Hello, I think I can fix above problem with this command `pip install -e git+https://github.com/huggingface/nanotron.git@df57f21deb0af6b923b5bec773be9eb15c5391f7#egg=nanotron`

**Comment by Na00s** [comment]
Deleting all the dependencies and cloning all the repos from scratch fixed the issue for me. Thanks !

**Comment by barney49** [comment]
hello @Na00s 
did you have a good weekend?

actually, I am going to evaluate my own fineweb dataset using lighteval and nanotron
I've got this model checkpoints
![image](https://github.com/user-attachments/assets/72763375-c5e3-4e08-98e0-ab037b3132bd)
how to evaluate this? I am going to use `lighteval nanotron --checkpoint-config-path './checkpoints/10/config.yaml'`
could you help this problem?

**Comment by Na00s** [comment]
Hey,

Hope all is well.

To be honest I can't really understand your model's config from the screenshot.

The way I did it was push my models to the HF hub then run an sh file that looks something like this:

accelerate launch --multi_gpu --num_processes=<num_gpus> -m \
    lighteval accelerate \
    --model_args "pretrained=path to your model on the hub" \
    --use_chat_template \ # optional, if you want to run the evaluation with the chat template
    --tasks "extended|ifeval|0|0" \
    --output_dir "./evals"

**Comment by jeffra** [comment]
@xrsrke is it possible to push out a new v0.5 release of nanotron to pypi? Currently the https://github.com/huggingface/lighteval examples are broken due to this issue.

**Comment by xrsrke** [comment]
@jeffra sure, ill push it in a couple of hours
