### ISSUE TITLE
[Bug] `TypeError: Config.__init__() [...]` from `examples/config_tiny_llama.py`

### ISSUE THREAD

**Issue by saforem2** [huggingface/nanotron#35]
Fixed by #33 

For reference:

> I was getting TypeError: Config.__init__() missing 1 required positional argument: profiler' when trying to run examples/config_tiny_llama.py.
> 
> Explicitly:
> 
> ```
> $ python3 examples/config_tiny_llama.py
> Model has 16p4K parameters
> Traceback (most recent call last):
>   File "/lus/grand/projects/datascience/foremans/locations/polaris/projects/saforem2/nanotron/examples/config_tiny_llama.py", line 90, in <module>
>     config = Config(
> TypeError: Config.__init__() missing 1 required positional argument: 'profiler'
> [1]    30778 exit 1     python3 examples/config_tiny_llama.py
> 2.78s user 5.53s system 231% cpu 3.590s total
> ```
> 
> the issue is coming from this line in the Config object in src/nanotron/config/config.py:
> 
> https://github.com/huggingface/nanotron/blob/main/src/nanotron/config/config.py#L334
> 
> Setting the Optional[ProfilerArgs] = None by default (as shown below) fixes this:
> 
> ```python
> @dataclass
> class Config:
>     # [...]
>     profiler: Optional[ProfilerArgs] = None
> ```

**Comment by thomwolf** [comment]
thanks for the issue, `Setting the Optional[ProfilerArgs] = None by default` prevent subclassing the Config in other training scripts though, which is usefull to add features without making `nanotron` too big.

So best will probably be to add `profiler = None` in `examples/config_tiny_llama.py` if you can open a PR for this.
Cc @NouamaneTazi

**Comment by saforem2** [comment]
ahh okay, yeah that makes sense. that was actually what I did [here initially](https://github.com/huggingface/nanotron/pull/33/commits/0b2ce45d75aa0d61a3d84c944529c529146394b9) before reverting it.

@thomwolf, @NouamaneTazi this should be resolved following these two commits:

- [7ed240ba](https://github.com/huggingface/nanotron/pull/33/commits/7ed240ba570b427cce64b673f3425a595cccd0dd): Removes `Optional[ProfilerArgs] = None`
- [8d52b084](https://github.com/huggingface/nanotron/pull/33/commits/8d52b084838cec8609dc4913509908516247d108): Sets `profiler=None` in `Config(...)`

**Comment by NouamaneTazi** [comment]
Thanks for the issue & fix 🤗
