### ISSUE TITLE
Continued Pretraining on Llama7b.

### ISSUE THREAD

**Issue by wiseyy** [huggingface/nanotron#78]
I want to do continued pretraining on my custom dataset, using the weights of Llama7b in the HF format. How do I initialize the model with those weights? I think there isn't a function for that yet.

**Comment by xrsrke** [comment]
Hey, you have to convert it to nanotron checkpoint format!!

**Comment by wiseyy** [comment]
I converted the weights as you mentioned, but unfortunately, I cannot get sane outputs for the pretrained llama weights as I get when using HF Api. I am trying to figure out why that is happening. Conversion is straightforward except for the gate_up and qkv weights of nanotron, since the structure of the weights is not mentioned. I assume that concatenating the hf weights in the 0th dimension in the order (gate, up) and (q,k,v) should give the same behaviour for nanotron weights.

The sources of errors I could think of are (assuming there is no bug in run_generate.py):
1. Order of qkv matrices in the nanotron format.
2. Storing the transpose of qkv matrices?
3. Difference in rotary embeddings as compared to HF API.

Could you please help me out?
